# Generated by Django 3.0.4 on 2020-03-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
