# Generated by Django 3.0.4 on 2020-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0005_auto_20200312_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
